version: "3.7"

services:
  db:
    image: postgres:12.3
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  backend: &backend
    restart: always
    command: start-backend
    image: emenu-api
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    logging:
      options:
        max-size: "200k"

  rabbitmq:
    restart: always
    image: rabbitmq:3.8.6
    expose:
      - "5672"

  worker:
    <<: *backend
    ports: [ ]
    command: start-celery worker -l INFO -Q default

  beat:
    <<: *backend
    ports: [ ]
    command: start-celery beat -l INFO

volumes:
  pg-data:
