# Generated by Django 3.2.9 on 2021-11-03 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='menu',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menus.menu'
            ),
        ),
    ]
