# Generated by Django 3.2.9 on 2021-11-04 09:49

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', Decimal('0'))), name='dish_price_positive'),
        ),
    ]
